// Code generated by protoc-gen-go.
// source: cx.proto
// DO NOT EDIT!

/*
Package cxpb is a generated protocol buffer package.

It is generated from these files:
	cx.proto

It has these top-level messages:
	Fragment
	NumberVerification
	MetaData
	KeyValue
	Parameter
	Node
	Edge
	NodeAttribute
	EdgeAttribute
	NetworkAttribute
	CartesianLayout
	AnonymousAspect
*/
package cxpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Fragment struct {
	// Types that are valid to be assigned to Element:
	//	*Fragment_NumberVerification
	//	*Fragment_Metadata
	//	*Fragment_Parameter
	//	*Fragment_Aspect
	//	*Fragment_Node
	//	*Fragment_Edge
	//	*Fragment_NodeAttribute
	//	*Fragment_EdgeAttribute
	//	*Fragment_NetworkAttribute
	//	*Fragment_CartesianLayout
	Element isFragment_Element `protobuf_oneof:"element"`
}

func (m *Fragment) Reset()                    { *m = Fragment{} }
func (m *Fragment) String() string            { return proto.CompactTextString(m) }
func (*Fragment) ProtoMessage()               {}
func (*Fragment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isFragment_Element interface {
	isFragment_Element()
}

type Fragment_NumberVerification struct {
	NumberVerification *NumberVerification `protobuf:"bytes,1,opt,name=numberVerification,oneof"`
}
type Fragment_Metadata struct {
	Metadata *MetaData `protobuf:"bytes,2,opt,name=metadata,oneof"`
}
type Fragment_Parameter struct {
	Parameter *Parameter `protobuf:"bytes,3,opt,name=parameter,oneof"`
}
type Fragment_Aspect struct {
	Aspect *AnonymousAspect `protobuf:"bytes,4,opt,name=aspect,oneof"`
}
type Fragment_Node struct {
	Node *Node `protobuf:"bytes,5,opt,name=node,oneof"`
}
type Fragment_Edge struct {
	Edge *Edge `protobuf:"bytes,6,opt,name=edge,oneof"`
}
type Fragment_NodeAttribute struct {
	NodeAttribute *NodeAttribute `protobuf:"bytes,7,opt,name=nodeAttribute,oneof"`
}
type Fragment_EdgeAttribute struct {
	EdgeAttribute *EdgeAttribute `protobuf:"bytes,8,opt,name=edgeAttribute,oneof"`
}
type Fragment_NetworkAttribute struct {
	NetworkAttribute *NetworkAttribute `protobuf:"bytes,9,opt,name=networkAttribute,oneof"`
}
type Fragment_CartesianLayout struct {
	CartesianLayout *CartesianLayout `protobuf:"bytes,10,opt,name=cartesianLayout,oneof"`
}

func (*Fragment_NumberVerification) isFragment_Element() {}
func (*Fragment_Metadata) isFragment_Element()           {}
func (*Fragment_Parameter) isFragment_Element()          {}
func (*Fragment_Aspect) isFragment_Element()             {}
func (*Fragment_Node) isFragment_Element()               {}
func (*Fragment_Edge) isFragment_Element()               {}
func (*Fragment_NodeAttribute) isFragment_Element()      {}
func (*Fragment_EdgeAttribute) isFragment_Element()      {}
func (*Fragment_NetworkAttribute) isFragment_Element()   {}
func (*Fragment_CartesianLayout) isFragment_Element()    {}

func (m *Fragment) GetElement() isFragment_Element {
	if m != nil {
		return m.Element
	}
	return nil
}

func (m *Fragment) GetNumberVerification() *NumberVerification {
	if x, ok := m.GetElement().(*Fragment_NumberVerification); ok {
		return x.NumberVerification
	}
	return nil
}

func (m *Fragment) GetMetadata() *MetaData {
	if x, ok := m.GetElement().(*Fragment_Metadata); ok {
		return x.Metadata
	}
	return nil
}

func (m *Fragment) GetParameter() *Parameter {
	if x, ok := m.GetElement().(*Fragment_Parameter); ok {
		return x.Parameter
	}
	return nil
}

func (m *Fragment) GetAspect() *AnonymousAspect {
	if x, ok := m.GetElement().(*Fragment_Aspect); ok {
		return x.Aspect
	}
	return nil
}

func (m *Fragment) GetNode() *Node {
	if x, ok := m.GetElement().(*Fragment_Node); ok {
		return x.Node
	}
	return nil
}

func (m *Fragment) GetEdge() *Edge {
	if x, ok := m.GetElement().(*Fragment_Edge); ok {
		return x.Edge
	}
	return nil
}

func (m *Fragment) GetNodeAttribute() *NodeAttribute {
	if x, ok := m.GetElement().(*Fragment_NodeAttribute); ok {
		return x.NodeAttribute
	}
	return nil
}

func (m *Fragment) GetEdgeAttribute() *EdgeAttribute {
	if x, ok := m.GetElement().(*Fragment_EdgeAttribute); ok {
		return x.EdgeAttribute
	}
	return nil
}

func (m *Fragment) GetNetworkAttribute() *NetworkAttribute {
	if x, ok := m.GetElement().(*Fragment_NetworkAttribute); ok {
		return x.NetworkAttribute
	}
	return nil
}

func (m *Fragment) GetCartesianLayout() *CartesianLayout {
	if x, ok := m.GetElement().(*Fragment_CartesianLayout); ok {
		return x.CartesianLayout
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Fragment) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Fragment_OneofMarshaler, _Fragment_OneofUnmarshaler, _Fragment_OneofSizer, []interface{}{
		(*Fragment_NumberVerification)(nil),
		(*Fragment_Metadata)(nil),
		(*Fragment_Parameter)(nil),
		(*Fragment_Aspect)(nil),
		(*Fragment_Node)(nil),
		(*Fragment_Edge)(nil),
		(*Fragment_NodeAttribute)(nil),
		(*Fragment_EdgeAttribute)(nil),
		(*Fragment_NetworkAttribute)(nil),
		(*Fragment_CartesianLayout)(nil),
	}
}

func _Fragment_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Fragment)
	// element
	switch x := m.Element.(type) {
	case *Fragment_NumberVerification:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NumberVerification); err != nil {
			return err
		}
	case *Fragment_Metadata:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Metadata); err != nil {
			return err
		}
	case *Fragment_Parameter:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Parameter); err != nil {
			return err
		}
	case *Fragment_Aspect:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Aspect); err != nil {
			return err
		}
	case *Fragment_Node:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Node); err != nil {
			return err
		}
	case *Fragment_Edge:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Edge); err != nil {
			return err
		}
	case *Fragment_NodeAttribute:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NodeAttribute); err != nil {
			return err
		}
	case *Fragment_EdgeAttribute:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EdgeAttribute); err != nil {
			return err
		}
	case *Fragment_NetworkAttribute:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NetworkAttribute); err != nil {
			return err
		}
	case *Fragment_CartesianLayout:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CartesianLayout); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Fragment.Element has unexpected type %T", x)
	}
	return nil
}

func _Fragment_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Fragment)
	switch tag {
	case 1: // element.numberVerification
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NumberVerification)
		err := b.DecodeMessage(msg)
		m.Element = &Fragment_NumberVerification{msg}
		return true, err
	case 2: // element.metadata
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MetaData)
		err := b.DecodeMessage(msg)
		m.Element = &Fragment_Metadata{msg}
		return true, err
	case 3: // element.parameter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Parameter)
		err := b.DecodeMessage(msg)
		m.Element = &Fragment_Parameter{msg}
		return true, err
	case 4: // element.aspect
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AnonymousAspect)
		err := b.DecodeMessage(msg)
		m.Element = &Fragment_Aspect{msg}
		return true, err
	case 5: // element.node
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Node)
		err := b.DecodeMessage(msg)
		m.Element = &Fragment_Node{msg}
		return true, err
	case 6: // element.edge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Edge)
		err := b.DecodeMessage(msg)
		m.Element = &Fragment_Edge{msg}
		return true, err
	case 7: // element.nodeAttribute
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NodeAttribute)
		err := b.DecodeMessage(msg)
		m.Element = &Fragment_NodeAttribute{msg}
		return true, err
	case 8: // element.edgeAttribute
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EdgeAttribute)
		err := b.DecodeMessage(msg)
		m.Element = &Fragment_EdgeAttribute{msg}
		return true, err
	case 9: // element.networkAttribute
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NetworkAttribute)
		err := b.DecodeMessage(msg)
		m.Element = &Fragment_NetworkAttribute{msg}
		return true, err
	case 10: // element.cartesianLayout
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CartesianLayout)
		err := b.DecodeMessage(msg)
		m.Element = &Fragment_CartesianLayout{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Fragment_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Fragment)
	// element
	switch x := m.Element.(type) {
	case *Fragment_NumberVerification:
		s := proto.Size(x.NumberVerification)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Fragment_Metadata:
		s := proto.Size(x.Metadata)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Fragment_Parameter:
		s := proto.Size(x.Parameter)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Fragment_Aspect:
		s := proto.Size(x.Aspect)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Fragment_Node:
		s := proto.Size(x.Node)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Fragment_Edge:
		s := proto.Size(x.Edge)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Fragment_NodeAttribute:
		s := proto.Size(x.NodeAttribute)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Fragment_EdgeAttribute:
		s := proto.Size(x.EdgeAttribute)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Fragment_NetworkAttribute:
		s := proto.Size(x.NetworkAttribute)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Fragment_CartesianLayout:
		s := proto.Size(x.CartesianLayout)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type NumberVerification struct {
	LongNumber int64 `protobuf:"varint,1,opt,name=longNumber" json:"longNumber,omitempty"`
}

func (m *NumberVerification) Reset()                    { *m = NumberVerification{} }
func (m *NumberVerification) String() string            { return proto.CompactTextString(m) }
func (*NumberVerification) ProtoMessage()               {}
func (*NumberVerification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NumberVerification) GetLongNumber() int64 {
	if m != nil {
		return m.LongNumber
	}
	return 0
}

type MetaData struct {
	Name             string      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Version          string      `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	IdCounter        int64       `protobuf:"varint,3,opt,name=idCounter" json:"idCounter,omitempty"`
	ElementCount     int64       `protobuf:"varint,4,opt,name=elementCount" json:"elementCount,omitempty"`
	ConsistencyGroup int64       `protobuf:"varint,5,opt,name=consistencyGroup" json:"consistencyGroup,omitempty"`
	Checksum         int64       `protobuf:"varint,6,opt,name=checksum" json:"checksum,omitempty"`
	Properties       []*KeyValue `protobuf:"bytes,7,rep,name=properties" json:"properties,omitempty"`
}

func (m *MetaData) Reset()                    { *m = MetaData{} }
func (m *MetaData) String() string            { return proto.CompactTextString(m) }
func (*MetaData) ProtoMessage()               {}
func (*MetaData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MetaData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetaData) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *MetaData) GetIdCounter() int64 {
	if m != nil {
		return m.IdCounter
	}
	return 0
}

func (m *MetaData) GetElementCount() int64 {
	if m != nil {
		return m.ElementCount
	}
	return 0
}

func (m *MetaData) GetConsistencyGroup() int64 {
	if m != nil {
		return m.ConsistencyGroup
	}
	return 0
}

func (m *MetaData) GetChecksum() int64 {
	if m != nil {
		return m.Checksum
	}
	return 0
}

func (m *MetaData) GetProperties() []*KeyValue {
	if m != nil {
		return m.Properties
	}
	return nil
}

type KeyValue struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *KeyValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *KeyValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Parameter struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Parameter) Reset()                    { *m = Parameter{} }
func (m *Parameter) String() string            { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()               {}
func (*Parameter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Parameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Parameter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Node struct {
	Id         int64  `protobuf:"varint,1,opt,name=id,json=@id" json:"id,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,json=n" json:"name,omitempty"`
	Represents string `protobuf:"bytes,3,opt,name=represents,json=r" json:"represents,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Node) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetRepresents() string {
	if m != nil {
		return m.Represents
	}
	return ""
}

type Edge struct {
	Id          int64  `protobuf:"varint,1,opt,name=id,json=@id" json:"id,omitempty"`
	SourceId    int64  `protobuf:"varint,2,opt,name=sourceId,json=s" json:"sourceId,omitempty"`
	TargetId    int64  `protobuf:"varint,3,opt,name=targetId,json=t" json:"targetId,omitempty"`
	Interaction string `protobuf:"bytes,4,opt,name=interaction,json=i" json:"interaction,omitempty"`
}

func (m *Edge) Reset()                    { *m = Edge{} }
func (m *Edge) String() string            { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()               {}
func (*Edge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Edge) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Edge) GetSourceId() int64 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *Edge) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *Edge) GetInteraction() string {
	if m != nil {
		return m.Interaction
	}
	return ""
}

type NodeAttribute struct {
	NodeId   int64  `protobuf:"varint,1,opt,name=nodeId,json=po" json:"nodeId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,json=n" json:"name,omitempty"`
	Value    string `protobuf:"bytes,3,opt,name=value,json=v" json:"value,omitempty"`
	Type     string `protobuf:"bytes,4,opt,name=type,json=d" json:"type,omitempty"`
	SubnetId int64  `protobuf:"varint,5,opt,name=subnetId,json=s" json:"subnetId,omitempty"`
}

func (m *NodeAttribute) Reset()                    { *m = NodeAttribute{} }
func (m *NodeAttribute) String() string            { return proto.CompactTextString(m) }
func (*NodeAttribute) ProtoMessage()               {}
func (*NodeAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *NodeAttribute) GetNodeId() int64 {
	if m != nil {
		return m.NodeId
	}
	return 0
}

func (m *NodeAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *NodeAttribute) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NodeAttribute) GetSubnetId() int64 {
	if m != nil {
		return m.SubnetId
	}
	return 0
}

type EdgeAttribute struct {
	EdgeId   int64  `protobuf:"varint,1,opt,name=edgeId,json=po" json:"edgeId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,json=n" json:"name,omitempty"`
	Value    string `protobuf:"bytes,3,opt,name=value,json=v" json:"value,omitempty"`
	Type     string `protobuf:"bytes,4,opt,name=type,json=d" json:"type,omitempty"`
	SubnetId int64  `protobuf:"varint,5,opt,name=subnetId,json=s" json:"subnetId,omitempty"`
}

func (m *EdgeAttribute) Reset()                    { *m = EdgeAttribute{} }
func (m *EdgeAttribute) String() string            { return proto.CompactTextString(m) }
func (*EdgeAttribute) ProtoMessage()               {}
func (*EdgeAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *EdgeAttribute) GetEdgeId() int64 {
	if m != nil {
		return m.EdgeId
	}
	return 0
}

func (m *EdgeAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EdgeAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *EdgeAttribute) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *EdgeAttribute) GetSubnetId() int64 {
	if m != nil {
		return m.SubnetId
	}
	return 0
}

type NetworkAttribute struct {
	EdgeId   int64  `protobuf:"varint,1,opt,name=edgeId,json=po" json:"edgeId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,json=n" json:"name,omitempty"`
	Value    string `protobuf:"bytes,3,opt,name=value,json=v" json:"value,omitempty"`
	Type     string `protobuf:"bytes,4,opt,name=type,json=d" json:"type,omitempty"`
	SubnetId int64  `protobuf:"varint,5,opt,name=subnetId,json=s" json:"subnetId,omitempty"`
}

func (m *NetworkAttribute) Reset()                    { *m = NetworkAttribute{} }
func (m *NetworkAttribute) String() string            { return proto.CompactTextString(m) }
func (*NetworkAttribute) ProtoMessage()               {}
func (*NetworkAttribute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *NetworkAttribute) GetEdgeId() int64 {
	if m != nil {
		return m.EdgeId
	}
	return 0
}

func (m *NetworkAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NetworkAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *NetworkAttribute) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NetworkAttribute) GetSubnetId() int64 {
	if m != nil {
		return m.SubnetId
	}
	return 0
}

type CartesianLayout struct {
	Nodeid int64   `protobuf:"varint,1,opt,name=nodeid" json:"nodeid,omitempty"`
	X      float64 `protobuf:"fixed64,2,opt,name=x" json:"x,omitempty"`
	Y      float64 `protobuf:"fixed64,3,opt,name=y" json:"y,omitempty"`
	Viewid int64   `protobuf:"varint,4,opt,name=viewid" json:"viewid,omitempty"`
}

func (m *CartesianLayout) Reset()                    { *m = CartesianLayout{} }
func (m *CartesianLayout) String() string            { return proto.CompactTextString(m) }
func (*CartesianLayout) ProtoMessage()               {}
func (*CartesianLayout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CartesianLayout) GetNodeid() int64 {
	if m != nil {
		return m.Nodeid
	}
	return 0
}

func (m *CartesianLayout) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *CartesianLayout) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *CartesianLayout) GetViewid() int64 {
	if m != nil {
		return m.Viewid
	}
	return 0
}

type AnonymousAspect struct {
	Type    string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Element []byte `protobuf:"bytes,2,opt,name=element,proto3" json:"element,omitempty"`
}

func (m *AnonymousAspect) Reset()                    { *m = AnonymousAspect{} }
func (m *AnonymousAspect) String() string            { return proto.CompactTextString(m) }
func (*AnonymousAspect) ProtoMessage()               {}
func (*AnonymousAspect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AnonymousAspect) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AnonymousAspect) GetElement() []byte {
	if m != nil {
		return m.Element
	}
	return nil
}

func init() {
	proto.RegisterType((*Fragment)(nil), "cxpb.Fragment")
	proto.RegisterType((*NumberVerification)(nil), "cxpb.NumberVerification")
	proto.RegisterType((*MetaData)(nil), "cxpb.MetaData")
	proto.RegisterType((*KeyValue)(nil), "cxpb.KeyValue")
	proto.RegisterType((*Parameter)(nil), "cxpb.Parameter")
	proto.RegisterType((*Node)(nil), "cxpb.Node")
	proto.RegisterType((*Edge)(nil), "cxpb.Edge")
	proto.RegisterType((*NodeAttribute)(nil), "cxpb.NodeAttribute")
	proto.RegisterType((*EdgeAttribute)(nil), "cxpb.EdgeAttribute")
	proto.RegisterType((*NetworkAttribute)(nil), "cxpb.NetworkAttribute")
	proto.RegisterType((*CartesianLayout)(nil), "cxpb.CartesianLayout")
	proto.RegisterType((*AnonymousAspect)(nil), "cxpb.AnonymousAspect")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CyService service

type CyServiceClient interface {
	StreamFragments(ctx context.Context, opts ...grpc.CallOption) (CyService_StreamFragmentsClient, error)
}

type cyServiceClient struct {
	cc *grpc.ClientConn
}

func NewCyServiceClient(cc *grpc.ClientConn) CyServiceClient {
	return &cyServiceClient{cc}
}

func (c *cyServiceClient) StreamFragments(ctx context.Context, opts ...grpc.CallOption) (CyService_StreamFragmentsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CyService_serviceDesc.Streams[0], c.cc, "/cxpb.CyService/StreamFragments", opts...)
	if err != nil {
		return nil, err
	}
	x := &cyServiceStreamFragmentsClient{stream}
	return x, nil
}

type CyService_StreamFragmentsClient interface {
	Send(*Fragment) error
	Recv() (*Fragment, error)
	grpc.ClientStream
}

type cyServiceStreamFragmentsClient struct {
	grpc.ClientStream
}

func (x *cyServiceStreamFragmentsClient) Send(m *Fragment) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cyServiceStreamFragmentsClient) Recv() (*Fragment, error) {
	m := new(Fragment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for CyService service

type CyServiceServer interface {
	StreamFragments(CyService_StreamFragmentsServer) error
}

func RegisterCyServiceServer(s *grpc.Server, srv CyServiceServer) {
	s.RegisterService(&_CyService_serviceDesc, srv)
}

func _CyService_StreamFragments_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CyServiceServer).StreamFragments(&cyServiceStreamFragmentsServer{stream})
}

type CyService_StreamFragmentsServer interface {
	Send(*Fragment) error
	Recv() (*Fragment, error)
	grpc.ServerStream
}

type cyServiceStreamFragmentsServer struct {
	grpc.ServerStream
}

func (x *cyServiceStreamFragmentsServer) Send(m *Fragment) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cyServiceStreamFragmentsServer) Recv() (*Fragment, error) {
	m := new(Fragment)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cxpb.CyService",
	HandlerType: (*CyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFragments",
			Handler:       _CyService_StreamFragments_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cx.proto",
}

func init() { proto.RegisterFile("cx.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 723 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x95, 0x4d, 0x4f, 0xf3, 0x46,
	0x10, 0xc7, 0xed, 0xd8, 0x24, 0xf6, 0x00, 0x4d, 0xb4, 0x14, 0x64, 0xa1, 0xaa, 0x42, 0x3e, 0xa1,
	0xaa, 0x0a, 0x15, 0xa5, 0xea, 0xa1, 0x07, 0x9a, 0x02, 0xad, 0xe9, 0x9b, 0xaa, 0x45, 0x42, 0xea,
	0xa1, 0x87, 0x8d, 0x3d, 0x4d, 0x2d, 0xe2, 0x5d, 0x6b, 0xbd, 0x0e, 0xf1, 0x37, 0xeb, 0xe7, 0x7a,
	0x3e, 0xc1, 0xa3, 0x5d, 0xaf, 0xf3, 0xca, 0xe5, 0x39, 0x70, 0xf3, 0xcc, 0xfc, 0xe6, 0x65, 0xbd,
	0xff, 0xb1, 0x21, 0x48, 0x97, 0xe3, 0x52, 0x0a, 0x25, 0x88, 0x9f, 0x2e, 0xcb, 0x69, 0xfc, 0xbf,
	0x0f, 0xc1, 0xcf, 0x92, 0xcd, 0x0a, 0xe4, 0x8a, 0xfc, 0x0a, 0x84, 0xd7, 0xc5, 0x14, 0xe5, 0x33,
	0xca, 0xfc, 0xdf, 0x3c, 0x65, 0x2a, 0x17, 0x3c, 0x72, 0x2f, 0xdc, 0xcb, 0xc3, 0xeb, 0x68, 0xac,
	0xf9, 0xf1, 0x9f, 0x7b, 0xf1, 0xc4, 0xa1, 0x6f, 0x64, 0x91, 0xaf, 0x21, 0x28, 0x50, 0xb1, 0x8c,
	0x29, 0x16, 0xf5, 0x4c, 0x85, 0xcf, 0xda, 0x0a, 0x7f, 0xa0, 0x62, 0xf7, 0x4c, 0xb1, 0xc4, 0xa1,
	0x2b, 0x82, 0x5c, 0x41, 0x58, 0x32, 0xc9, 0x0a, 0x54, 0x28, 0x23, 0xcf, 0xe0, 0xc3, 0x16, 0xff,
	0xab, 0x73, 0x27, 0x0e, 0x5d, 0x33, 0xe4, 0x0a, 0xfa, 0xac, 0x2a, 0x31, 0x55, 0x91, 0x6f, 0xe8,
	0xd3, 0x96, 0x9e, 0x70, 0xc1, 0x9b, 0x42, 0xd4, 0xd5, 0xc4, 0x04, 0x13, 0x87, 0x5a, 0x8c, 0x5c,
	0x80, 0xcf, 0x45, 0x86, 0xd1, 0x81, 0xc1, 0xc1, 0x9e, 0x46, 0x64, 0x98, 0x38, 0xd4, 0x44, 0x34,
	0x81, 0xd9, 0x0c, 0xa3, 0xfe, 0x26, 0xf1, 0x90, 0xcd, 0x0c, 0xa1, 0x23, 0xe4, 0x07, 0x38, 0xd6,
	0xe4, 0x44, 0x29, 0x99, 0x4f, 0x6b, 0x85, 0xd1, 0xc0, 0xa0, 0x27, 0xeb, 0x62, 0xab, 0x50, 0xe2,
	0xd0, 0x6d, 0x56, 0x27, 0xeb, 0x22, 0xeb, 0xe4, 0x60, 0x33, 0xf9, 0x61, 0x33, 0xa4, 0x93, 0xb7,
	0x58, 0x72, 0x0f, 0x23, 0x8e, 0xea, 0x55, 0xc8, 0x97, 0x75, 0x7e, 0x68, 0xf2, 0xcf, 0x6c, 0xf3,
	0x9d, 0x68, 0xe2, 0xd0, 0xbd, 0x0c, 0x32, 0x81, 0x61, 0xca, 0xa4, 0xc2, 0x2a, 0x67, 0xfc, 0x77,
	0xd6, 0x88, 0x5a, 0x45, 0xb0, 0xf9, 0xf6, 0xee, 0xb6, 0x83, 0x89, 0x43, 0x77, 0xf9, 0x9f, 0x42,
	0x18, 0xe0, 0x1c, 0xb5, 0x5a, 0xe2, 0x1b, 0x20, 0xfb, 0x6a, 0x20, 0x5f, 0x02, 0xcc, 0x05, 0x9f,
	0xb5, 0x11, 0xa3, 0x1d, 0x8f, 0x6e, 0x78, 0xe2, 0x0f, 0x2e, 0x04, 0x9d, 0x04, 0x08, 0x01, 0x9f,
	0xb3, 0x02, 0x0d, 0x16, 0x52, 0xf3, 0x4c, 0x22, 0x18, 0x2c, 0x50, 0x56, 0x5a, 0x79, 0x3d, 0xe3,
	0xee, 0x4c, 0xf2, 0x05, 0x84, 0x79, 0x76, 0x27, 0x6a, 0xde, 0x89, 0xc4, 0xa3, 0x6b, 0x07, 0x89,
	0xe1, 0xc8, 0x4e, 0x66, 0x3c, 0x46, 0x17, 0x1e, 0xdd, 0xf2, 0x91, 0xaf, 0x60, 0x94, 0x0a, 0x5e,
	0xe5, 0x95, 0x42, 0x9e, 0x36, 0xbf, 0x48, 0x51, 0x97, 0x46, 0x10, 0x1e, 0xdd, 0xf3, 0x93, 0x73,
	0x08, 0xd2, 0xff, 0x30, 0x7d, 0xa9, 0xea, 0xc2, 0x48, 0xc2, 0xa3, 0x2b, 0x9b, 0x8c, 0x01, 0x4a,
	0x29, 0x4a, 0x94, 0x2a, 0xc7, 0x2a, 0x1a, 0x5c, 0x78, 0x6b, 0x79, 0xff, 0x86, 0xcd, 0x33, 0x9b,
	0xd7, 0x48, 0x37, 0x88, 0xf8, 0x06, 0x82, 0xce, 0xff, 0xe6, 0x99, 0x3f, 0x87, 0x83, 0x85, 0x0e,
	0xda, 0x13, 0xb7, 0x46, 0xfc, 0x1d, 0x84, 0x2b, 0xf5, 0x7f, 0x42, 0xda, 0x2d, 0xf8, 0x5a, 0x8a,
	0x64, 0x08, 0xbd, 0x3c, 0xb3, 0x37, 0xe0, 0xfd, 0x98, 0x67, 0x64, 0x68, 0x4b, 0xb4, 0xb4, 0xcb,
	0xc9, 0x29, 0x80, 0xc4, 0x52, 0x62, 0x85, 0x5c, 0x55, 0xe6, 0x8d, 0x86, 0xd4, 0x95, 0xf1, 0xdf,
	0xe0, 0x6b, 0x39, 0xee, 0x17, 0x38, 0x81, 0xa0, 0x12, 0xb5, 0x4c, 0xf1, 0x31, 0x33, 0x45, 0x3c,
	0xea, 0x56, 0xda, 0xa9, 0x98, 0x9c, 0xa1, 0x7a, 0xcc, 0xec, 0xa5, 0xb8, 0x8a, 0x9c, 0xc1, 0x61,
	0xae, 0x6f, 0x85, 0xa5, 0xe6, 0x13, 0xe2, 0xb7, 0xa5, 0xf3, 0x78, 0x0e, 0xc7, 0x5b, 0x6b, 0x42,
	0x08, 0xf4, 0xf5, 0x9a, 0x3c, 0x76, 0x7d, 0x7a, 0xa5, 0xd8, 0x9f, 0x73, 0xd4, 0x9d, 0xd3, 0x8e,
	0xb8, 0xd0, 0x88, 0x6a, 0x4a, 0xec, 0x0a, 0xb7, 0xa3, 0xd5, 0x53, 0x6e, 0xa6, 0x38, 0xb0, 0xa3,
	0xe9, 0x6e, 0x5b, 0x7b, 0xa5, 0xbb, 0xe9, 0xbd, 0x7a, 0x9f, 0x6e, 0x02, 0x46, 0xbb, 0x5b, 0xf8,
	0xbe, 0x0d, 0xff, 0x81, 0xe1, 0xce, 0xc6, 0x92, 0xb3, 0xf6, 0x75, 0xae, 0xae, 0xcd, 0x5a, 0xe4,
	0x08, 0xdc, 0xa5, 0x69, 0xe8, 0x52, 0x77, 0xa9, 0xad, 0xc6, 0x34, 0x73, 0xa9, 0xdb, 0xe8, 0x9c,
	0x45, 0x8e, 0xaf, 0x79, 0x66, 0x57, 0xc6, 0x5a, 0xf1, 0x2d, 0x0c, 0x77, 0x3e, 0xa7, 0x5a, 0x84,
	0x66, 0x2e, 0x2b, 0x42, 0xfd, 0xac, 0xf7, 0xd5, 0xee, 0x98, 0x69, 0x70, 0x44, 0x3b, 0xf3, 0xfa,
	0x1e, 0xc2, 0xbb, 0xe6, 0x09, 0xe5, 0x22, 0x4f, 0x91, 0x7c, 0x0f, 0xc3, 0x27, 0x25, 0x91, 0x15,
	0xdd, 0xdf, 0xa6, 0x22, 0x76, 0x63, 0x3a, 0xc7, 0xf9, 0x8e, 0x1d, 0x3b, 0x97, 0xee, 0x37, 0xee,
	0xb4, 0x6f, 0x7e, 0x57, 0xdf, 0x7e, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x71, 0x45, 0x2e, 0x6f, 0xba,
	0x06, 0x00, 0x00,
}
